Repository kubero-dev/kubero, pull requests merged in 2023-04, with the labels that each got.

#138 Template / Add hopscotch template
  services/hopscotch/app.yaml
  services/hopscotch/service.yaml
Labels: template

#141 Release/v1.9.4
  client/src/App.vue
  client/src/components/addons/list.vue
  client/src/components/apps/detail.vue
  client/src/components/apps/events.vue
  client/src/components/apps/new.vue
  client/src/components/apps/vulnerabilities.vue
  client/src/components/events/view.vue
  client/src/components/pipelines/appcard.vue
  client/src/components/pipelines/detail.vue
  client/src/components/pipelines/list.vue
  client/src/components/services/list.vue
  client/src/plugins/vuetify.js
Labels: release

#142 Fix wp service repository
  services/wordpress/app.yaml
Labels: bug

#144 Deployment strategy toggle button
  client/src/components/apps/new.vue
Labels: enhancement

#145 Release/v1.9.5
  client/src/components/apps/new.vue
Labels: release

#146 Template / Add Laravel framework
  services/laravel/app.yaml
  services/laravel/service.yaml
Labels: template

#153 Template / Add symfony template
  services/symfony/app.yaml
  services/symfony/service.yaml
Labels: template

#147 Template / Add Etherpad
  services/etherpad/app.yaml
  services/etherpad/service.yaml
Labels: template

#148 Template / Add Rallly template
  services/rallly/app.yaml
  services/rallly/service.yaml
Labels: template

#149 Template / Add tasksmd template
  services/tasksmd/app.yaml
  services/tasksmd/service.yaml
Labels: template

#150 Template / Add opengist template
  services/opengist/app.yaml
  services/opengist/service.yaml
Labels: template

#151 Template / Add coral commenting application
  services/coral/app.yaml
  services/coral/service.yaml
Labels: template

#154 Template / Add languagetool template
  services/languagetool/app.yaml
  services/languagetool/service.yaml
Labels: template

#155 Template / Add illa template
  services/illa/app.yaml
  services/illa/service.yaml
Labels: template
