Repository kubero-dev/kubero, pull requests merged in 2023-08, with the labels that each got.

#188 Feature / Improve Navigation
  client/src/components/apps/detail.vue
  client/src/components/apps/new.vue
  client/src/components/breadcrumbs.vue
  client/src/components/pipelines/appcard.vue
  client/src/components/pipelines/detail.vue
  client/src/components/pipelines/list.vue
Labels: enhancement

#190 Fix templates desc + fix img
  services/changedetection/service.yaml
  services/grafana/service.yaml
  services/shiori/service.yaml
Labels: bug

#189 Feature / Improve logs view
  client/src/App.vue
  client/src/components/apps/detail.vue
  client/src/components/apps/logs.vue
  client/src/components/apps/logstab.vue
  client/src/router/index.js
  src/kubero.ts
  src/routes/logs.ts
  swagger.js
  swagger.json
Labels: enhancement

#192 fix(api/gogs): better git uri parsing
  package.json
  src/git/gogs.ts
  yarn.lock
Labels: bug, enhancement

#193 fix(api/gogs): 2 fixes in gogs webhook handling
  src/git/gogs.ts
  src/routes/repo.ts
Labels: bug

#195 Fix/m1m1x/gogs git url parsing
  package.json
  src/git/bitbucket.ts
  src/git/gitea.ts
  src/git/github.ts
  src/git/gitlab.ts
  src/git/gogs.ts
  yarn.lock
Labels: bug

#194 fix(buildpack/python): do not try to create venv in a readonly environment
  config.yaml
Labels: bug

#196 Template / add sshwifty
  services/sshwifty/app.yaml
  services/sshwifty/service.yaml
Labels: template

#197 Template / add httpbin-go
  services/go-httpbin/app.yaml
  services/go-httpbin/service.yaml
Labels: template

#199 Template / add chartmuseum
  services/chartmuseum/app.yaml
  services/chartmuseum/service.yaml
Labels: template
