Repository kubero-dev/kubero, pull requests merged in 2023-05, with the labels that each got.

#160 Template / Add Maputnik
  services/maputnik/app.yaml
  services/maputnik/service.yaml
Labels: template

#161 Template / Add Gitea
  services/gitea/app.yaml
  services/gitea/service.yaml
Labels: template

#162 Template / Add nats template
  services/nats/app.yaml
  services/nats/service.yaml
Labels: template

#164 Fix / Show only results if an scan exists
  client/src/components/apps/vulnerabilities.vue
Labels: bug

#165 Fix / improve postgresql form
  src/addons/kuberoPostgresql.ts
Labels: bug

#167 Feature / Improve docker compose
  .env.template
  codecov.yaml
  docker-compose.dev.yaml
  docker-compose.yaml
  kind.yaml
Labels: enhancement

#166 Feature / add Haraka mail server as a add-on
  client/public/img/addons/Haraka.png
  client/public/img/addons/HarakaTxt.png
  src/addons/kuberoMail.ts
  src/modules/addons.ts
Labels: enhancement

#168 Feature / Improve pipeline creation
  client/src/components/pipelines/new.vue
Labels: enhancement

#171 Fix / Endless spinner during vuln scan
  client/src/components/apps/vulnerabilities.vue
  src/kubero.ts
Labels: bug

#172 Fix / Improve pipeline delete
  client/src/components/pipelines/list.vue
  src/kubero.ts
Labels: bug

#169 Template / Add unleash, feature toggles
  services/unleash/app.yaml
  services/unleash/service.yaml
Labels: template
