Repository kubero-dev/kubero, pull requests merged in 2024-03, with the labels that each got.

#290 Set all switches to primary color
  client/src/components/apps/addons.vue
  client/src/components/apps/form.vue
  client/src/components/pipelines/form.vue
Labels: bug

#281 feature / improve welcome message
  client/src/components/pipelines/list.vue
Labels: enhancement

#292 New service account annotation feature.
  client/src/components/apps/appstats.vue
  client/src/components/apps/form.vue
  server/src/kubero.ts
  server/src/modules/application.ts
  server/src/modules/kubectl.ts
  server/src/routes/apps.ts
  server/src/routes/pipelines.ts
  server/src/types.ts
  server/swagger.json
Labels: enhancement

#305 Feature/new serviceaccount annotations
  client/src/components/apps/appstats.vue
  client/src/components/apps/form.vue
  server/src/kubero.ts
  server/src/modules/application.ts
  server/src/modules/kubectl.ts
  server/src/routes/apps.ts
  server/src/routes/pipelines.ts
  server/src/types.ts
  server/swagger.json
Labels: enhancement

#300 fix: prevent usage of 'new' keyword
  client/src/components/pipelines/form.vue
Labels: bug

#302 Feat/environment values file upload
  client/src/components/apps/form.vue
  client/src/components/pipelines/form.vue
Labels: enhancement

#307 Release/v2.1.0
  .gitignore
  client/src/components/apps/appstats.vue
  client/src/components/apps/detail.vue
  client/src/components/apps/form.vue
  client/src/components/breadcrumbs.vue
  client/src/components/pipelines/detail.vue
  client/src/components/pipelines/list.vue
  client/src/components/settings/form-buildpacks-item.vue
  client/src/components/settings/form-buildpacks.vue
  client/src/components/settings/form-deployment.vue
  client/src/components/settings/form-general.vue
  client/src/components/settings/form-podsizes.vue
  client/src/components/settings/form-templates.vue
  client/src/components/settings/form.vue
  client/src/layouts/default/AppBar.vue
  client/src/layouts/default/NavDrawer.vue
  client/src/layouts/default/View.vue
  client/src/plugins/vuetify.ts
  client/src/stores/kubero.ts
  server/.env.template
  server/config.yaml.example
  server/src/configure.ts
  server/src/kubero.ts
  server/src/modules/application.ts
  server/src/modules/config.ts
  server/src/modules/kubectl.ts
  server/src/modules/settings.ts
  server/src/routes/apps.ts
  server/src/routes/auth.ts
  server/src/routes/pipelines.ts
  server/src/routes/settings.ts
  server/src/types.ts
  server/swagger.json
  services/grafana/app.yaml
Labels: release
