Repository kubero-dev/kubero, pull requests merged in 2024-05, with the labels that each got.

#340 feat: add ISSUE TEMPLATES
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/pull_request_template.md
Labels: enhancement

#342 Feature/add longterm metrics
  client/package.json
  client/src/components/apps/detail.vue
  client/src/components/apps/metrics.vue
  client/yarn.lock
  server/.env.template
  server/package.json
  server/src/addons/plugin.ts
  server/src/configure.ts
  server/src/modules/audit.ts
  server/src/modules/metrics.ts
  server/src/routes/logs.ts
  server/src/routes/metrics.ts
  server/yarn.lock
Labels: enhancement

#345 Feature/add rsshub
  services/rsshub/app.yaml
  services/rsshub/service.yaml
Labels: template

#347 Template / add leantime
  services/leantime/app.yaml
  services/leantime/service.yaml
Labels: template

#343 Release/v2.3.0
  client/src/components/apps/alerts.vue
  client/src/components/apps/detail.vue
  client/src/components/apps/metrics.vue
  client/src/layouts/default/View.vue
  client/src/stores/kubero.ts
  client/yarn.lock
  server/src/configure.ts
  server/src/kubero.ts
  server/src/modules/metrics.ts
  server/src/routes/auth.ts
  server/src/routes/metrics.ts
  server/yarn.lock
Labels: release
