Repository kubero-dev/kubero, pull requests merged in 2024-02, with the labels that each got.

#275 Feature/container console
  client/package.json
  client/src/components/activity/view.vue
  client/src/components/apps/console.vue
  client/src/components/apps/detail.vue
  client/src/layouts/default/Popup.vue
  client/src/layouts/default/View.vue
  client/src/router/index.ts
  client/src/stores/kubero.ts
  client/yarn.lock
  server/config.yaml
  server/src/kubero.ts
  server/src/modules/kubectl.ts
  server/src/routes/auth.ts
  server/src/routes/logs.ts
  server/src/socket.ts
  server/src/types.ts
Labels: enhancement

#278 Template / Add it-tools
  services/it-tools/app.yaml
  services/it-tools/service.yaml
Labels: template

#282 Maintenance/upgrade packages
  client/yarn.lock
  server/yarn.lock
Labels: maintenance

#283 Allow configuration of oauth2 scopes
  server/.env.template
  server/.env.test
  server/src/modules/auth.ts
  server/src/routes/auth.ts
Labels: enhancement
