Repository kubero-dev/kubero, pull requests merged in 2024-09, with the labels that each got.

#411 add template for evershop
  services/evershop/app.yaml
  services/evershop/service.yaml
Labels: template

#414 add template for sqlpad
  services/sqlpad/app.yaml
  services/sqlpad/service.yaml
  services/statping-ng/service.yaml
Labels: template

#415 [typo] Update eventsAudit.vue
  client/src/components/apps/eventsAudit.vue
Labels: bug

#403 Release/v2.4.2
  README.md
  client/package.json
  client/public/img/addons/CouchDB.png
  client/public/img/addons/Kafka.png
  client/public/img/addons/Minio.png
  client/public/img/addons/RabbitMQ.svg
  client/public/img/addons/cloudflare.svg
  client/public/img/addons/couchdb.svg
  client/public/img/addons/elasticsearch.svg
  client/public/img/addons/kafka.svg
  client/public/img/addons/mariadb.svg
  client/public/img/addons/memcached.svg
  client/public/img/addons/mongo.svg
  client/public/img/addons/mysql.svg
  client/public/img/addons/pgsql.svg
  client/public/img/addons/redis.svg
  client/src/components/addons/index.vue
  client/src/components/pipelines/appcard.vue
  client/vite.config.ts
  client/yarn.lock
  server/package.json
  server/src/addons/kuberoCouchDB.ts
  server/src/addons/kuberoElasticsearch.ts
  server/src/addons/kuberoKafka.ts
  server/src/addons/kuberoMemcached.ts
  server/src/addons/kuberoMongoDB.ts
  server/src/addons/kuberoMysql.ts
  server/src/addons/kuberoPostgresql.ts
  server/src/addons/kuberoRabbitMQ.ts
  server/src/addons/kuberoRedis.ts
  server/src/addons/mongoDB.ts
  server/src/addons/mongoDBCluster.ts
  server/src/addons/postgresCluster.ts
  server/src/addons/redis.ts
  server/src/addons/redisCluster.ts
  server/src/modules/kubectl.ts
  server/yarn.lock
Labels: release
