Repository kubero-dev/kubero, pull requests merged in 2024-11, with the labels that each got.

#451 Template/add kanboard
  services/kanboard/app.yaml
  services/kanboard/service.yaml
Labels: template

#470 Feature / Add field for command when deploying container images
  client/src/components/apps/form.vue
  server/src/modules/application.ts
  server/src/routes/apps.ts
  server/src/types.ts
Labels: enhancement

#471 Template / Add template for atuin
  services/atuin/app.yaml
  services/atuin/service.yaml
Labels: template

#473 fix race condition in app form
  client/src/components/apps/form.vue
Labels: bug

#479 Template / Add ChartDB
  services/chartdb/chartdb.yaml
  services/chartdb/service.yaml
Labels: template

#481 Feature / Use singlefile templates
  client/src/components/apps/form.vue
  client/src/components/settings/form-templates.vue
  client/src/components/templates/index.vue
  server/src/kubero.ts
  server/src/modules/config.ts
  server/src/routes/templates.ts
  server/src/types.ts
Labels: enhancement

#467 Template / Add node-mark
  services/note-mark/app.yaml
  services/note-mark/service.yaml
Labels: template

#468 add template for filestash
  services/filestash/app.yaml
  services/filestash/service.yaml
Labels: template

#469 feat: adding typesense service
  services/typesense/app.yaml
  services/typesense/service.yaml
Labels: template

#487 Feature/minor frontend improvements
  client/src/components/pipelines/form.vue
  server/src/git/repo.ts
  server/src/modules/kubectl.ts
  server/src/modules/repositories.ts
  server/src/routes/repo.ts
Labels: enhancement

#443 Release/v2.4.4
  client/src/components/apps/form.vue
  client/src/components/pipelines/form.vue
  client/src/components/settings/form-templates.vue
  client/src/components/templates/index.vue
  client/src/layouts/default/NavDrawer.vue
  client/src/layouts/default/View.vue
  client/src/stores/kubero.ts
  server/src/git/repo.ts
  server/src/kubero.ts
  server/src/modules/application.ts
  server/src/modules/config.ts
  server/src/modules/kubectl.ts
  server/src/modules/repositories.ts
  server/src/modules/templates/buildpacks.yaml
  server/src/routes/apps.ts
  server/src/routes/auth.ts
  server/src/routes/repo.ts
  server/src/routes/templates.ts
  server/src/types.ts
Labels: release

#489 Template / Add StatusNook
  services/statusnook/app.yaml
  services/statusnook/service.yaml
Labels: template

#501 Template / Add Ciao
  services/ciao/app.yaml
Labels: template

#490 improve template download
  server/src/modules/application.ts
  server/src/types.ts
Labels: enhancement

#507 Template / Add Claper
  services/claper/claper.yaml
Labels: template

#508 Template / Add Docmost
  services/docmost/app.yaml
Labels: template

#513 Template / Add Elasticvue
  services/elasticvue/app.yaml
Labels: template

#491 Template / Add Chatpad
  services/chatpad/app.yaml
Labels: template

#492 Template / Add Anse
  services/anse/app.yaml
Labels: template

#529 Template / Add Slash
  services/slash/app.yaml
Labels: template

#518 Fix / Cors headers not applied
  client/src/components/apps/form.vue
Labels: bug

#510 Template / Add Zipline
  services/zipline/app.yaml
Labels: template

#521 Template / Add Redisinsight
  services/redisinsight/app.yaml
Labels: template

#515 Template / Add 2FAuth
  services/twofauth/app.yaml
Labels: template

#525 Template / Add Azzimut
  services/azzimut/app.yaml
Labels: template

#522 Template / Add vvveb mysql
  services/vvveb.mysql/app.yaml
Labels: template

#519 Template / Add Corteza
  services/corteza/app.yaml
Labels: template

#530 Template / Add jsoncrack
  services/jsoncrack/app.yaml
Labels: template
